/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CtfRouteImport } from './routes/ctf'
import { Route as DarkwebRouteImport } from './routes/darkweb'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as EasmRouteImport } from './routes/easm'
import { Route as EdrRouteImport } from './routes/edr'
import { Route as IrRouteImport } from './routes/ir'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as PacketAnalyzerRouteImport } from './routes/packet-analyzer'
import { Route as PentestRouteImport } from './routes/pentest'
import { Route as PhishingRouteImport } from './routes/phishing'
import { Route as PostureRouteImport } from './routes/posture'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PtaasRouteImport } from './routes/ptaas'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocSimulatorRouteImport } from './routes/soc-simulator'
import { Route as SupplyChainRouteImport } from './routes/supply-chain'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ThreatIntelRouteImport } from './routes/threat-Intel'
import { Route as WarroomRouteImport } from './routes/warroom'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as LabsAdNetworkRouteImport } from './routes/labs.ad-network'
import { Route as LabsBruteRouteImport } from './routes/labs.brute'
import { Route as LabsCsrfRouteImport } from './routes/labs.csrf'
import { Route as LabsDdosRouteImport } from './routes/labs.ddos'
import { Route as LabsIamPrivescRouteImport } from './routes/labs.iam-privesc'
import { Route as LabsIdorRouteImport } from './routes/labs.idor'
import { Route as LabsJuiceshopRouteImport } from './routes/labs.juiceshop'
import { Route as LabsJwtRouteImport } from './routes/labs.jwt'
import { Route as LabsLfiRouteImport } from './routes/labs.lfi'
import { Route as LabsMisconfigRouteImport } from './routes/labs.misconfig'
import { Route as LabsPhishingPayloadRouteImport } from './routes/labs.phishing-payload'
import { Route as LabsRansomwareRouteImport } from './routes/labs.ransomware'
import { Route as LabsRceRouteImport } from './routes/labs.rce'
import { Route as LabsSqliRouteImport } from './routes/labs.sqli'
import { Route as LabsSsrfRouteImport } from './routes/labs.ssrf'
import { Route as LabsTerminalRouteImport } from './routes/labs.terminal'
import { Route as LabsXssRouteImport } from './routes/labs.xss'
import { Route as LabsXxeRouteImport } from './routes/labs.xxe'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicEdrIngestRouteImport } from './routes/api/public/edr/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CtfRoute = CtfRouteImport.update({
  id: '/ctf',
  path: '/ctf',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkwebRoute = DarkwebRouteImport.update({
  id: '/darkweb',
  path: '/darkweb',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const EasmRoute = EasmRouteImport.update({
  id: '/easm',
  path: '/easm',
  getParentRoute: () => rootRouteImport,
} as any)
const EdrRoute = EdrRouteImport.update({
  id: '/edr',
  path: '/edr',
  getParentRoute: () => rootRouteImport,
} as any)
const IrRoute = IrRouteImport.update({
  id: '/ir',
  path: '/ir',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketAnalyzerRoute = PacketAnalyzerRouteImport.update({
  id: '/packet-analyzer',
  path: '/packet-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PentestRoute = PentestRouteImport.update({
  id: '/pentest',
  path: '/pentest',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingRoute = PhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostureRoute = PostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PtaasRoute = PtaasRouteImport.update({
  id: '/ptaas',
  path: '/ptaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocSimulatorRoute = SocSimulatorRouteImport.update({
  id: '/soc-simulator',
  path: '/soc-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyChainRoute = SupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-Intel',
  path: '/threat-Intel',
  getParentRoute: () => rootRouteImport,
} as any)
const WarroomRoute = WarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabsRoute,
} as any)
const LabsAdNetworkRoute = LabsAdNetworkRouteImport.update({
  id: '/ad-network',
  path: '/ad-network',
  getParentRoute: () => LabsRoute,
} as any)
const LabsBruteRoute = LabsBruteRouteImport.update({
  id: '/brute',
  path: '/brute',
  getParentRoute: () => LabsRoute,
} as any)
const LabsCsrfRoute = LabsCsrfRouteImport.update({
  id: '/csrf',
  path: '/csrf',
  getParentRoute: () => LabsRoute,
} as any)
const LabsDdosRoute = LabsDdosRouteImport.update({
  id: '/ddos',
  path: '/ddos',
  getParentRoute: () => LabsRoute,
} as any)
const LabsIamPrivescRoute = LabsIamPrivescRouteImport.update({
  id: '/iam-privesc',
  path: '/iam-privesc',
  getParentRoute: () => LabsRoute,
} as any)
const LabsIdorRoute = LabsIdorRouteImport.update({
  id: '/idor',
  path: '/idor',
  getParentRoute: () => LabsRoute,
} as any)
const LabsJuiceshopRoute = LabsJuiceshopRouteImport.update({
  id: '/juiceshop',
  path: '/juiceshop',
  getParentRoute: () => LabsRoute,
} as any)
const LabsJwtRoute = LabsJwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => LabsRoute,
} as any)
const LabsLfiRoute = LabsLfiRouteImport.update({
  id: '/lfi',
  path: '/lfi',
  getParentRoute: () => LabsRoute,
} as any)
const LabsMisconfigRoute = LabsMisconfigRouteImport.update({
  id: '/misconfig',
  path: '/misconfig',
  getParentRoute: () => LabsRoute,
} as any)
const LabsPhishingPayloadRoute = LabsPhishingPayloadRouteImport.update({
  id: '/phishing-payload',
  path: '/phishing-payload',
  getParentRoute: () => LabsRoute,
} as any)
const LabsRansomwareRoute = LabsRansomwareRouteImport.update({
  id: '/ransomware',
  path: '/ransomware',
  getParentRoute: () => LabsRoute,
} as any)
const LabsRceRoute = LabsRceRouteImport.update({
  id: '/rce',
  path: '/rce',
  getParentRoute: () => LabsRoute,
} as any)
const LabsSqliRoute = LabsSqliRouteImport.update({
  id: '/sqli',
  path: '/sqli',
  getParentRoute: () => LabsRoute,
} as any)
const LabsSsrfRoute = LabsSsrfRouteImport.update({
  id: '/ssrf',
  path: '/ssrf',
  getParentRoute: () => LabsRoute,
} as any)
const LabsTerminalRoute = LabsTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => LabsRoute,
} as any)
const LabsXssRoute = LabsXssRouteImport.update({
  id: '/xss',
  path: '/xss',
  getParentRoute: () => LabsRoute,
} as any)
const LabsXxeRoute = LabsXxeRouteImport.update({
  id: '/xxe',
  path: '/xxe',
  getParentRoute: () => LabsRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEdrIngestRoute = ApiPublicEdrIngestRouteImport.update({
  id: '/api/public/edr/ingest',
  path: '/api/public/edr/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/ctf': typeof CtfRoute
  '/darkweb': typeof DarkwebRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/easm': typeof EasmRoute
  '/edr': typeof EdrRoute
  '/ir': typeof IrRoute
  '/labs': typeof LabsRouteWithChildren
  '/learning': typeof LearningRoute
  '/packet-analyzer': typeof PacketAnalyzerRoute
  '/pentest': typeof PentestRoute
  '/phishing': typeof PhishingRoute
  '/posture': typeof PostureRoute
  '/pricing': typeof PricingRoute
  '/ptaas': typeof PtaasRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/soc-simulator': typeof SocSimulatorRoute
  '/supply-chain': typeof SupplyChainRoute
  '/teams': typeof TeamsRoute
  '/threat-Intel': typeof ThreatIntelRoute
  '/warroom': typeof WarroomRoute
  '/labs/ad-network': typeof LabsAdNetworkRoute
  '/labs/brute': typeof LabsBruteRoute
  '/labs/csrf': typeof LabsCsrfRoute
  '/labs/ddos': typeof LabsDdosRoute
  '/labs/iam-privesc': typeof LabsIamPrivescRoute
  '/labs/idor': typeof LabsIdorRoute
  '/labs/juiceshop': typeof LabsJuiceshopRoute
  '/labs/jwt': typeof LabsJwtRoute
  '/labs/lfi': typeof LabsLfiRoute
  '/labs/misconfig': typeof LabsMisconfigRoute
  '/labs/phishing-payload': typeof LabsPhishingPayloadRoute
  '/labs/ransomware': typeof LabsRansomwareRoute
  '/labs/rce': typeof LabsRceRoute
  '/labs/sqli': typeof LabsSqliRoute
  '/labs/ssrf': typeof LabsSsrfRoute
  '/labs/terminal': typeof LabsTerminalRoute
  '/labs/xss': typeof LabsXssRoute
  '/labs/xxe': typeof LabsXxeRoute
  '/labs/': typeof LabsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/edr/ingest': typeof ApiPublicEdrIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/ctf': typeof CtfRoute
  '/darkweb': typeof DarkwebRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/easm': typeof EasmRoute
  '/edr': typeof EdrRoute
  '/ir': typeof IrRoute
  '/learning': typeof LearningRoute
  '/packet-analyzer': typeof PacketAnalyzerRoute
  '/pentest': typeof PentestRoute
  '/phishing': typeof PhishingRoute
  '/posture': typeof PostureRoute
  '/pricing': typeof PricingRoute
  '/ptaas': typeof PtaasRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/soc-simulator': typeof SocSimulatorRoute
  '/supply-chain': typeof SupplyChainRoute
  '/teams': typeof TeamsRoute
  '/threat-Intel': typeof ThreatIntelRoute
  '/warroom': typeof WarroomRoute
  '/labs/ad-network': typeof LabsAdNetworkRoute
  '/labs/brute': typeof LabsBruteRoute
  '/labs/csrf': typeof LabsCsrfRoute
  '/labs/ddos': typeof LabsDdosRoute
  '/labs/iam-privesc': typeof LabsIamPrivescRoute
  '/labs/idor': typeof LabsIdorRoute
  '/labs/juiceshop': typeof LabsJuiceshopRoute
  '/labs/jwt': typeof LabsJwtRoute
  '/labs/lfi': typeof LabsLfiRoute
  '/labs/misconfig': typeof LabsMisconfigRoute
  '/labs/phishing-payload': typeof LabsPhishingPayloadRoute
  '/labs/ransomware': typeof LabsRansomwareRoute
  '/labs/rce': typeof LabsRceRoute
  '/labs/sqli': typeof LabsSqliRoute
  '/labs/ssrf': typeof LabsSsrfRoute
  '/labs/terminal': typeof LabsTerminalRoute
  '/labs/xss': typeof LabsXssRoute
  '/labs/xxe': typeof LabsXxeRoute
  '/labs': typeof LabsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/edr/ingest': typeof ApiPublicEdrIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/ctf': typeof CtfRoute
  '/darkweb': typeof DarkwebRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/easm': typeof EasmRoute
  '/edr': typeof EdrRoute
  '/ir': typeof IrRoute
  '/labs': typeof LabsRouteWithChildren
  '/learning': typeof LearningRoute
  '/packet-analyzer': typeof PacketAnalyzerRoute
  '/pentest': typeof PentestRoute
  '/phishing': typeof PhishingRoute
  '/posture': typeof PostureRoute
  '/pricing': typeof PricingRoute
  '/ptaas': typeof PtaasRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/soc-simulator': typeof SocSimulatorRoute
  '/supply-chain': typeof SupplyChainRoute
  '/teams': typeof TeamsRoute
  '/threat-Intel': typeof ThreatIntelRoute
  '/warroom': typeof WarroomRoute
  '/labs/ad-network': typeof LabsAdNetworkRoute
  '/labs/brute': typeof LabsBruteRoute
  '/labs/csrf': typeof LabsCsrfRoute
  '/labs/ddos': typeof LabsDdosRoute
  '/labs/iam-privesc': typeof LabsIamPrivescRoute
  '/labs/idor': typeof LabsIdorRoute
  '/labs/juiceshop': typeof LabsJuiceshopRoute
  '/labs/jwt': typeof LabsJwtRoute
  '/labs/lfi': typeof LabsLfiRoute
  '/labs/misconfig': typeof LabsMisconfigRoute
  '/labs/phishing-payload': typeof LabsPhishingPayloadRoute
  '/labs/ransomware': typeof LabsRansomwareRoute
  '/labs/rce': typeof LabsRceRoute
  '/labs/sqli': typeof LabsSqliRoute
  '/labs/ssrf': typeof LabsSsrfRoute
  '/labs/terminal': typeof LabsTerminalRoute
  '/labs/xss': typeof LabsXssRoute
  '/labs/xxe': typeof LabsXxeRoute
  '/labs/': typeof LabsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/edr/ingest': typeof ApiPublicEdrIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/assistant'
    | '/auth'
    | '/billing'
    | '/compliance'
    | '/ctf'
    | '/darkweb'
    | '/dashboard'
    | '/developer'
    | '/easm'
    | '/edr'
    | '/ir'
    | '/labs'
    | '/learning'
    | '/packet-analyzer'
    | '/pentest'
    | '/phishing'
    | '/posture'
    | '/pricing'
    | '/ptaas'
    | '/replay'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/soc-simulator'
    | '/supply-chain'
    | '/teams'
    | '/threat-Intel'
    | '/warroom'
    | '/labs/ad-network'
    | '/labs/brute'
    | '/labs/csrf'
    | '/labs/ddos'
    | '/labs/iam-privesc'
    | '/labs/idor'
    | '/labs/juiceshop'
    | '/labs/jwt'
    | '/labs/lfi'
    | '/labs/misconfig'
    | '/labs/phishing-payload'
    | '/labs/ransomware'
    | '/labs/rce'
    | '/labs/sqli'
    | '/labs/ssrf'
    | '/labs/terminal'
    | '/labs/xss'
    | '/labs/xxe'
    | '/labs/'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/api/public/edr/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/assistant'
    | '/auth'
    | '/billing'
    | '/compliance'
    | '/ctf'
    | '/darkweb'
    | '/dashboard'
    | '/developer'
    | '/easm'
    | '/edr'
    | '/ir'
    | '/learning'
    | '/packet-analyzer'
    | '/pentest'
    | '/phishing'
    | '/posture'
    | '/pricing'
    | '/ptaas'
    | '/replay'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/soc-simulator'
    | '/supply-chain'
    | '/teams'
    | '/threat-Intel'
    | '/warroom'
    | '/labs/ad-network'
    | '/labs/brute'
    | '/labs/csrf'
    | '/labs/ddos'
    | '/labs/iam-privesc'
    | '/labs/idor'
    | '/labs/juiceshop'
    | '/labs/jwt'
    | '/labs/lfi'
    | '/labs/misconfig'
    | '/labs/phishing-payload'
    | '/labs/ransomware'
    | '/labs/rce'
    | '/labs/sqli'
    | '/labs/ssrf'
    | '/labs/terminal'
    | '/labs/xss'
    | '/labs/xxe'
    | '/labs'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/api/public/edr/ingest'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/assistant'
    | '/auth'
    | '/billing'
    | '/compliance'
    | '/ctf'
    | '/darkweb'
    | '/dashboard'
    | '/developer'
    | '/easm'
    | '/edr'
    | '/ir'
    | '/labs'
    | '/learning'
    | '/packet-analyzer'
    | '/pentest'
    | '/phishing'
    | '/posture'
    | '/pricing'
    | '/ptaas'
    | '/replay'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/soc-simulator'
    | '/supply-chain'
    | '/teams'
    | '/threat-Intel'
    | '/warroom'
    | '/labs/ad-network'
    | '/labs/brute'
    | '/labs/csrf'
    | '/labs/ddos'
    | '/labs/iam-privesc'
    | '/labs/idor'
    | '/labs/juiceshop'
    | '/labs/jwt'
    | '/labs/lfi'
    | '/labs/misconfig'
    | '/labs/phishing-payload'
    | '/labs/ransomware'
    | '/labs/rce'
    | '/labs/sqli'
    | '/labs/ssrf'
    | '/labs/terminal'
    | '/labs/xss'
    | '/labs/xxe'
    | '/labs/'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/api/public/edr/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ComplianceRoute: typeof ComplianceRoute
  CtfRoute: typeof CtfRoute
  DarkwebRoute: typeof DarkwebRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  EasmRoute: typeof EasmRoute
  EdrRoute: typeof EdrRoute
  IrRoute: typeof IrRoute
  LabsRoute: typeof LabsRouteWithChildren
  LearningRoute: typeof LearningRoute
  PacketAnalyzerRoute: typeof PacketAnalyzerRoute
  PentestRoute: typeof PentestRoute
  PhishingRoute: typeof PhishingRoute
  PostureRoute: typeof PostureRoute
  PricingRoute: typeof PricingRoute
  PtaasRoute: typeof PtaasRoute
  ReplayRoute: typeof ReplayRoute
  ReportsRoute: typeof ReportsRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SocSimulatorRoute: typeof SocSimulatorRoute
  SupplyChainRoute: typeof SupplyChainRoute
  TeamsRoute: typeof TeamsRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  WarroomRoute: typeof WarroomRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicEdrIngestRoute: typeof ApiPublicEdrIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctf': {
      id: '/ctf'
      path: '/ctf'
      fullPath: '/ctf'
      preLoaderRoute: typeof CtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darkweb': {
      id: '/darkweb'
      path: '/darkweb'
      fullPath: '/darkweb'
      preLoaderRoute: typeof DarkwebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easm': {
      id: '/easm'
      path: '/easm'
      fullPath: '/easm'
      preLoaderRoute: typeof EasmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edr': {
      id: '/edr'
      path: '/edr'
      fullPath: '/edr'
      preLoaderRoute: typeof EdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ir': {
      id: '/ir'
      path: '/ir'
      fullPath: '/ir'
      preLoaderRoute: typeof IrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet-analyzer': {
      id: '/packet-analyzer'
      path: '/packet-analyzer'
      fullPath: '/packet-analyzer'
      preLoaderRoute: typeof PacketAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pentest': {
      id: '/pentest'
      path: '/pentest'
      fullPath: '/pentest'
      preLoaderRoute: typeof PentestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing': {
      id: '/phishing'
      path: '/phishing'
      fullPath: '/phishing'
      preLoaderRoute: typeof PhishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posture': {
      id: '/posture'
      path: '/posture'
      fullPath: '/posture'
      preLoaderRoute: typeof PostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptaas': {
      id: '/ptaas'
      path: '/ptaas'
      fullPath: '/ptaas'
      preLoaderRoute: typeof PtaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc-simulator': {
      id: '/soc-simulator'
      path: '/soc-simulator'
      fullPath: '/soc-simulator'
      preLoaderRoute: typeof SocSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-chain': {
      id: '/supply-chain'
      path: '/supply-chain'
      fullPath: '/supply-chain'
      preLoaderRoute: typeof SupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-Intel': {
      id: '/threat-Intel'
      path: '/threat-Intel'
      fullPath: '/threat-Intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warroom': {
      id: '/warroom'
      path: '/warroom'
      fullPath: '/warroom'
      preLoaderRoute: typeof WarroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/ad-network': {
      id: '/labs/ad-network'
      path: '/ad-network'
      fullPath: '/labs/ad-network'
      preLoaderRoute: typeof LabsAdNetworkRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/brute': {
      id: '/labs/brute'
      path: '/brute'
      fullPath: '/labs/brute'
      preLoaderRoute: typeof LabsBruteRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/csrf': {
      id: '/labs/csrf'
      path: '/csrf'
      fullPath: '/labs/csrf'
      preLoaderRoute: typeof LabsCsrfRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/ddos': {
      id: '/labs/ddos'
      path: '/ddos'
      fullPath: '/labs/ddos'
      preLoaderRoute: typeof LabsDdosRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/iam-privesc': {
      id: '/labs/iam-privesc'
      path: '/iam-privesc'
      fullPath: '/labs/iam-privesc'
      preLoaderRoute: typeof LabsIamPrivescRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/idor': {
      id: '/labs/idor'
      path: '/idor'
      fullPath: '/labs/idor'
      preLoaderRoute: typeof LabsIdorRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/juiceshop': {
      id: '/labs/juiceshop'
      path: '/juiceshop'
      fullPath: '/labs/juiceshop'
      preLoaderRoute: typeof LabsJuiceshopRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/jwt': {
      id: '/labs/jwt'
      path: '/jwt'
      fullPath: '/labs/jwt'
      preLoaderRoute: typeof LabsJwtRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/lfi': {
      id: '/labs/lfi'
      path: '/lfi'
      fullPath: '/labs/lfi'
      preLoaderRoute: typeof LabsLfiRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/misconfig': {
      id: '/labs/misconfig'
      path: '/misconfig'
      fullPath: '/labs/misconfig'
      preLoaderRoute: typeof LabsMisconfigRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/phishing-payload': {
      id: '/labs/phishing-payload'
      path: '/phishing-payload'
      fullPath: '/labs/phishing-payload'
      preLoaderRoute: typeof LabsPhishingPayloadRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/ransomware': {
      id: '/labs/ransomware'
      path: '/ransomware'
      fullPath: '/labs/ransomware'
      preLoaderRoute: typeof LabsRansomwareRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/rce': {
      id: '/labs/rce'
      path: '/rce'
      fullPath: '/labs/rce'
      preLoaderRoute: typeof LabsRceRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/sqli': {
      id: '/labs/sqli'
      path: '/sqli'
      fullPath: '/labs/sqli'
      preLoaderRoute: typeof LabsSqliRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/ssrf': {
      id: '/labs/ssrf'
      path: '/ssrf'
      fullPath: '/labs/ssrf'
      preLoaderRoute: typeof LabsSsrfRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/terminal': {
      id: '/labs/terminal'
      path: '/terminal'
      fullPath: '/labs/terminal'
      preLoaderRoute: typeof LabsTerminalRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/xss': {
      id: '/labs/xss'
      path: '/xss'
      fullPath: '/labs/xss'
      preLoaderRoute: typeof LabsXssRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/xxe': {
      id: '/labs/xxe'
      path: '/xxe'
      fullPath: '/labs/xxe'
      preLoaderRoute: typeof LabsXxeRouteImport
      parentRoute: typeof LabsRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/edr/ingest': {
      id: '/api/public/edr/ingest'
      path: '/api/public/edr/ingest'
      fullPath: '/api/public/edr/ingest'
      preLoaderRoute: typeof ApiPublicEdrIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabsRouteChildren {
  LabsAdNetworkRoute: typeof LabsAdNetworkRoute
  LabsBruteRoute: typeof LabsBruteRoute
  LabsCsrfRoute: typeof LabsCsrfRoute
  LabsDdosRoute: typeof LabsDdosRoute
  LabsIamPrivescRoute: typeof LabsIamPrivescRoute
  LabsIdorRoute: typeof LabsIdorRoute
  LabsJuiceshopRoute: typeof LabsJuiceshopRoute
  LabsJwtRoute: typeof LabsJwtRoute
  LabsLfiRoute: typeof LabsLfiRoute
  LabsMisconfigRoute: typeof LabsMisconfigRoute
  LabsPhishingPayloadRoute: typeof LabsPhishingPayloadRoute
  LabsRansomwareRoute: typeof LabsRansomwareRoute
  LabsRceRoute: typeof LabsRceRoute
  LabsSqliRoute: typeof LabsSqliRoute
  LabsSsrfRoute: typeof LabsSsrfRoute
  LabsTerminalRoute: typeof LabsTerminalRoute
  LabsXssRoute: typeof LabsXssRoute
  LabsXxeRoute: typeof LabsXxeRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsAdNetworkRoute: LabsAdNetworkRoute,
  LabsBruteRoute: LabsBruteRoute,
  LabsCsrfRoute: LabsCsrfRoute,
  LabsDdosRoute: LabsDdosRoute,
  LabsIamPrivescRoute: LabsIamPrivescRoute,
  LabsIdorRoute: LabsIdorRoute,
  LabsJuiceshopRoute: LabsJuiceshopRoute,
  LabsJwtRoute: LabsJwtRoute,
  LabsLfiRoute: LabsLfiRoute,
  LabsMisconfigRoute: LabsMisconfigRoute,
  LabsPhishingPayloadRoute: LabsPhishingPayloadRoute,
  LabsRansomwareRoute: LabsRansomwareRoute,
  LabsRceRoute: LabsRceRoute,
  LabsSqliRoute: LabsSqliRoute,
  LabsSsrfRoute: LabsSsrfRoute,
  LabsTerminalRoute: LabsTerminalRoute,
  LabsXssRoute: LabsXssRoute,
  LabsXxeRoute: LabsXxeRoute,
  LabsIndexRoute: LabsIndexRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ComplianceRoute: ComplianceRoute,
  CtfRoute: CtfRoute,
  DarkwebRoute: DarkwebRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  EasmRoute: EasmRoute,
  EdrRoute: EdrRoute,
  IrRoute: IrRoute,
  LabsRoute: LabsRouteWithChildren,
  LearningRoute: LearningRoute,
  PacketAnalyzerRoute: PacketAnalyzerRoute,
  PentestRoute: PentestRoute,
  PhishingRoute: PhishingRoute,
  PostureRoute: PostureRoute,
  PricingRoute: PricingRoute,
  PtaasRoute: PtaasRoute,
  ReplayRoute: ReplayRoute,
  ReportsRoute: ReportsRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SocSimulatorRoute: SocSimulatorRoute,
  SupplyChainRoute: SupplyChainRoute,
  TeamsRoute: TeamsRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  WarroomRoute: WarroomRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicEdrIngestRoute: ApiPublicEdrIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
