apiVersion: apps/v1
kind: Deployment
metadata:
  name: straxon-redis
  labels:
    app: straxon-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: straxon-redis
  template:
    metadata:
      labels:
        app: straxon-redis
    spec:
      containers:
      - name: straxon-redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: straxon-redis-service
spec:
  selector:
    app: straxon-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
